export const PRODUCTS = [
  'All Products','Medical','Nursing','Pre Med','SAT & ACT','AP ELA LOTE',
  'AP HISTORY','AP STATS','AP MATH','AP SCIENCE','Legal','CFA CMT',
  'CPA CMA','CPAC','CPA OLD','Pharmacy',
];

export const QBANK_LIST = [
  'USMLE Step 1', 'USMLE Step 2 CK', 'NCLEX-RN', 'NCLEX-PN',
  'CPA', 'CMA', 'CFA Level I', 'CFA Level II', 'MBE',
  'NAPLEX', 'SAT', 'ACT', 'AP Biology', 'AP Chemistry',
  'AP Physics 1', 'AP Calculus AB', 'AP Psychology', 'AP US History',
];

/** Parse "May 19, 2026 · 4:18 PM" → numeric ms for sorting. */
export function parseTs(ts: string): number {
  return new Date(ts.replace(/\s*·\s*/, ' ')).getTime() || 0;
}

export interface ThumbsRow {
  id: string; rating: 'up'|'down'; product: string; qbank: string|null;
  contentType: string; contentId: string|null;
  student: string; request: string; response: string; ts: string;
}

export interface GeneralRow {
  id: string; rating: number|null; product: string; qbank: string|null;
  student: string; ts: string; feedback: string;
  linked: null | { contentType: string; contentId: string|null; request: string; response: string; };
}

export interface FilterState {
  product: string[];
  qbank: string[];
  feedbackType: 'all'|'thumbs'|'general'|'general-with-prompt'|'general-without-prompt';
  thumbsDirection: 'all'|'up'|'down';
  ratingRange: string;       // 'any' | '0.0-0.9' | '1.0-1.9' | '2.0-2.9' | '3.0-3.9' | '4.0-5.0'
  contentType: string[];    // multi-select; 'none' = no content ID
  student: string;          // text search (partial match)
  userFilter: string;       // inline click filter (exact match)
  preset: 'today'|'3d'|'7d'|'30d'|null;
  dateStart: string; dateEnd: string;
}

export const DEFAULT_FILTERS: FilterState = {
  product: [], qbank: [], feedbackType: 'all', thumbsDirection: 'all',
  ratingRange: 'any', contentType: [], student: '', userFilter: '',
  preset: '30d', dateStart: '04/19/2026', dateEnd: '05/19/2026',
};

// ─────────────────────────────────────────────────────────────────────────────
//  THUMBS ROWS  (session field removed per spec)
// ─────────────────────────────────────────────────────────────────────────────
export const THUMBS_ROWS: ThumbsRow[] = [
  { id:'fb-7841', rating:'up',   product:'Medical',    qbank:'USMLE Step 2 CK',
    contentType:'Question',  contentId:'Q-1284',    student:'ipatel_03',
    request:'Why is the answer cabergoline and not bromocriptine for prolactinoma?',
    response:'Both are dopamine agonists, but cabergoline has higher selectivity for D2 receptors, longer half-life (~65 h), and superior tumor-shrinkage and prolactin-normalization rates (~80 %) in microadenomas. It is also better tolerated — less nausea and orthostasis. Bromocriptine remains preferred only when pregnancy is desired, as it has the longest safety record in gestation.',
    ts:'May 19, 2026 · 4:18 PM' },
  { id:'fb-7840', rating:'down', product:'Medical',    qbank:'USMLE Step 1',
    contentType:'Question',  contentId:'Q-9921',    student:'mkr_med24',
    request:'Walk me through the algorithm for new-onset atrial fibrillation in a hemodynamically stable patient.',
    response:'First, confirm with 12-lead ECG and assess hemodynamics — if unstable, synchronized cardioversion. In stable patients, control rate with a non-DHP CCB or beta-blocker, then risk-stratify for stroke using CHA2DS2-VASc and start anticoagulation if score ≥2 (men) / ≥3 (women). Rhythm control is considered for symptomatic AF or younger patients.',
    ts:'May 19, 2026 · 3:52 PM' },
  { id:'fb-7839', rating:'up',   product:'Nursing',    qbank:'NCLEX-RN',
    contentType:'Flashcard', contentId:'FC-552',    student:'rn_jasmine',
    request:'Quick recap on signs of digoxin toxicity?',
    response:'Look for the classic triad: GI (anorexia, nausea, vomiting), visual (yellow-green halos, blurred vision), and cardiac (bradycardia, AV block, ventricular ectopy). Hypokalemia potentiates toxicity. Therapeutic level is 0.5–2 ng/mL.',
    ts:'May 19, 2026 · 2:41 PM' },
  { id:'fb-7838', rating:'up',   product:'Pre Med',    qbank:'USMLE Step 1',
    contentType:'Lecture',   contentId:'L-118',     student:'premed_lucy',
    request:'Can you summarize the difference between competitive and non-competitive inhibition for the exam?',
    response:'Competitive inhibitors bind the active site, raising apparent Km but leaving Vmax unchanged — they can be out-competed by substrate. Non-competitive inhibitors bind an allosteric site, lowering Vmax with Km unchanged. On a Lineweaver-Burk plot, competitive lines intersect at the y-axis; non-competitive lines intersect at the x-axis.',
    ts:'May 19, 2026 · 1:20 PM' },
  { id:'fb-7837', rating:'down', product:'CPA CMA',    qbank:'CPA',
    contentType:'Question',  contentId:'Q-3412',    student:'cpa_blake',
    request:'Explain why this lease is classified as operating and not finance under ASC 842.',
    response:'Under ASC 842, a lessee classifies a lease as finance when any of five criteria are met (transfer of ownership, purchase option reasonably certain, lease term ≥ 75 % of useful life, PV of payments ≥ 90 % of fair value, or specialized asset). This lease meets none — the term is 4 of 10 years and PV is 62 % of fair value — so it is operating.',
    ts:'May 19, 2026 · 11:55 AM' },
  { id:'fb-7836', rating:'up',   product:'AP SCIENCE', qbank:'AP Biology',
    contentType:'Article',   contentId:'A-074',     student:'ap_neha',
    request:'How does the sodium-potassium pump actually use ATP?',
    response:'The pump is a P-type ATPase. Three Na+ bind from the cytoplasm, ATP phosphorylates an aspartate residue, the pump flips conformation and releases Na+ outside. Two K+ then bind, dephosphorylation flips it back, and K+ is released inside. Net: 3 Na+ out, 2 K+ in per ATP, generating the resting membrane potential.',
    ts:'May 19, 2026 · 10:33 AM' },
  { id:'fb-7835', rating:'down', product:'SAT & ACT',  qbank:'SAT',
    contentType:'Question',  contentId:'Q-S-218',   student:'satprep_olivia',
    request:'Why is choice (C) wrong for this rhetorical analysis passage?',
    response:'Choice (C) misreads the author\'s tone in lines 32–38 as critical. The diction ("deftly", "thoughtful") is admiring, not skeptical. The contrast is between the speaker\'s earlier and later views, not between the speaker and the subject. (B) is correct because it captures that shift.',
    ts:'May 19, 2026 · 9:14 AM' },
  { id:'fb-7834', rating:'up',   product:'CFA CMT',    qbank:'CFA Level I',
    contentType:'Lecture',   contentId:'L-CFA-22',  student:'cfa_ravi',
    request:'Refresh on Macaulay vs modified duration?',
    response:'Macaulay duration is the weighted-average time to receive a bond\'s cash flows, expressed in years. Modified duration = Macaulay / (1 + y/n) and approximates the % price change per 1 % change in yield. For a zero-coupon bond, Macaulay equals time to maturity.',
    ts:'May 18, 2026 · 6:02 PM' },
  { id:'fb-7833', rating:'up',   product:'Legal',      qbank:'MBE',
    contentType:'Question',  contentId:'Q-L-401',   student:'esquire_jordan',
    request:'Difference between specific and general intent for criminal law?',
    response:'Specific-intent crimes require an additional mental state beyond the actus reus (e.g. burglary requires intent to commit a felony inside). General-intent crimes only require intent to perform the act itself (e.g. battery). Voluntary intoxication is a defense to specific-intent only; mistake of fact need only be reasonable for general intent.',
    ts:'May 18, 2026 · 5:21 PM' },
  { id:'fb-7832', rating:'down', product:'AP HISTORY', qbank:'AP US History',
    contentType:'Article',   contentId:'A-USH-12',  student:'apush_mason',
    request:'Was the Compromise of 1850 really a Whig achievement?',
    response:'It\'s debated. While Clay (Whig) drafted it, Douglas (Democrat) actually shepherded the components through as separate bills after the omnibus failed. Most historians credit Douglas\'s procedural maneuver with passage, even though the Whig program drove the substance. So: partly.',
    ts:'May 18, 2026 · 4:46 PM' },
  { id:'fb-7831', rating:'up',   product:'Pharmacy',   qbank:'NAPLEX',
    contentType:'Flashcard', contentId:'FC-PH-89',  student:'pharmd_alex',
    request:'Renal dose adjustment for vancomycin in CrCl 30–50?',
    response:'Loading dose unchanged (25–30 mg/kg). Maintenance: 15–20 mg/kg every 24 h for CrCl 30–50, with trough goal 15–20 mg/L for severe MRSA. Always confirm with pharmacokinetic monitoring after 3rd–4th dose.',
    ts:'May 18, 2026 · 3:14 PM' },
  { id:'fb-7830', rating:'up',   product:'Nursing',    qbank:'NCLEX-RN',
    contentType:'Question',  contentId:'Q-N-771',   student:'rn_devon',
    request:'What\'s the priority nursing action for a client with suspected pulmonary embolism?',
    response:'Apply oxygen and elevate the head of the bed — airway/breathing comes first. Then notify the provider, prepare for anticoagulation, and obtain stat ABG, CT-PA, and D-dimer per protocol.',
    ts:'May 18, 2026 · 2:08 PM' },
  { id:'fb-7829', rating:'down', product:'Medical',    qbank:'USMLE Step 1',
    contentType:'Question',  contentId:'Q-1908',    student:'drchen_md',
    request:'When would you choose nitroprusside over labetalol in hypertensive emergency?',
    response:'Use nitroprusside when rapid, precisely titratable arterial and venous dilation is needed — e.g. acute aortic dissection alongside esmolol, or severe LV failure. Avoid in renal failure (thiocyanate accumulation) and prolonged use. Labetalol is preferred when beta-blockade is desired and tighter monitoring isn\'t available.',
    ts:'May 18, 2026 · 11:12 AM' },
  { id:'fb-7828', rating:'up',   product:'SAT & ACT',  qbank:'ACT',
    contentType:'Question',  contentId:'Q-A-094',   student:'act_taylor',
    request:'Trick for triangle similarity questions on ACT Math?',
    response:'Look for the AA shortcut first — if two angles match (often via parallel lines or shared angles), the triangles are similar. Then set up the ratio of corresponding sides. 80 % of ACT similarity questions resolve in two steps once you spot the parallel lines.',
    ts:'May 18, 2026 · 10:01 AM' },
  { id:'fb-7827', rating:'up',   product:'CPA CMA',    qbank:'CMA',
    contentType:'Article',   contentId:'A-CMA-31',  student:'cma_priya',
    request:'Standard cost variance — favorable vs unfavorable when actual quantity is higher?',
    response:'If actual quantity used exceeds standard quantity allowed for actual output, the quantity (usage) variance is unfavorable — you used more input than the standard permitted.',
    ts:'May 17, 2026 · 9:47 PM' },
  { id:'fb-7826', rating:'down', product:'AP MATH',    qbank:'AP Calculus AB',
    contentType:'Lecture',   contentId:'L-CAL-07',  student:'ap_riley',
    request:'Why does L\'Hôpital\'s rule need the indeterminate form check first?',
    response:'L\'Hôpital only applies to limits in the form 0/0 or ∞/∞. Applying it to a determinate form (e.g. 2/3) gives a wrong answer because you\'re differentiating something that already has a defined limit.',
    ts:'May 17, 2026 · 6:38 PM' },
  { id:'fb-7825', rating:'up',   product:'Medical',    qbank:'USMLE Step 2 CK',
    contentType:'Question',  contentId:'Q-1255',    student:'mvasquez_med',
    request:'Mechanism of pyridostigmine in myasthenia gravis?',
    response:'Pyridostigmine reversibly inhibits acetylcholinesterase at the neuromuscular junction, increasing ACh availability at nicotinic receptors. Since MG involves autoantibodies that reduce functional AChR, raising ACh partially overcomes the deficit and improves strength.',
    ts:'May 17, 2026 · 4:24 PM' },
  { id:'fb-7824', rating:'up',   product:'CPAC',       qbank:null,
    contentType:'—',         contentId:null,        student:'cpac_haruki',
    request:'Can you compare IFRS and US GAAP treatment of development costs?',
    response:'Under IFRS (IAS 38), development costs are capitalized once six criteria are met (technical feasibility, intent, ability to use/sell, future benefits, resources, reliable measurement). Under US GAAP, internal R&D is expensed as incurred with narrow exceptions.',
    ts:'May 17, 2026 · 1:18 PM' },
  { id:'fb-7823', rating:'down', product:'AP SCIENCE', qbank:'AP Chemistry',
    contentType:'Question',  contentId:'Q-AC-118',  student:'ap_chen',
    request:'Why does the equilibrium shift right when temperature drops here?',
    response:'The reaction is exothermic (ΔH < 0). Lowering temperature removes heat from the right side (a product), so by Le Châtelier\'s principle the equilibrium shifts right to produce more heat.',
    ts:'May 17, 2026 · 11:55 AM' },
  { id:'fb-7822', rating:'up',   product:'AP SCIENCE', qbank:'AP Psychology',
    contentType:'Flashcard', contentId:'FC-PSY-44', student:'psych_sam',
    request:'Quick distinction between classical and operant conditioning?',
    response:'Classical: pairing a neutral stimulus with one that already produces a response (Pavlov\'s dogs). Operant: behavior shaped by consequences — reinforcement increases behavior, punishment decreases it (Skinner).',
    ts:'May 17, 2026 · 10:22 AM' },
  { id:'fb-7821', rating:'up',   product:'Nursing',    qbank:'NCLEX-PN',
    contentType:'Question',  contentId:'Q-N-822',   student:'lpn_morgan',
    request:'Difference between metabolic and respiratory acidosis on a quick ABG?',
    response:'Look at pH and the matching primary. Metabolic acidosis: low pH, low HCO3- (primary), low PaCO2 (compensation). Respiratory acidosis: low pH, high PaCO2 (primary), high HCO3- (compensation in chronic).',
    ts:'May 17, 2026 · 9:08 AM' },
  { id:'fb-7820', rating:'down', product:'CFA CMT',    qbank:'CFA Level II',
    contentType:'Question',  contentId:'Q-CFA2-77', student:'cfa2_naomi',
    request:'When should I use H-model vs two-stage DDM?',
    response:'Use the H-model when growth declines linearly from a high initial rate to a stable long-run rate over a horizon H. Use two-stage DDM when growth changes abruptly between two distinct phases (high then stable).',
    ts:'May 16, 2026 · 8:41 PM' },
  { id:'fb-7819', rating:'up',   product:'Medical',    qbank:'USMLE Step 1',
    contentType:'Article',   contentId:'A-USML-09', student:'med_avery',
    request:'First-line workup for new microcytic anemia in an adult?',
    response:'Get iron studies (ferritin, serum iron, TIBC, % saturation) and reticulocyte count. Ferritin < 30 ng/mL is essentially diagnostic of iron deficiency. If ferritin is normal/high, consider thalassemia (Hb electrophoresis), anemia of chronic disease, or sideroblastic.',
    ts:'May 16, 2026 · 5:33 PM' },
  { id:'fb-7818', rating:'up',   product:'AP SCIENCE', qbank:'AP Physics 1',
    contentType:'Lecture',   contentId:'L-PHY-14',  student:'phys_jin',
    request:'When can I use conservation of momentum vs energy?',
    response:'Momentum is conserved in any collision with no external impulse (including inelastic collisions). Kinetic energy is conserved only in elastic collisions. So: use momentum always; use energy only when the collision is elastic.',
    ts:'May 16, 2026 · 3:14 PM' },
  { id:'fb-7817', rating:'down', product:'Legal',      qbank:'MBE',
    contentType:'Question',  contentId:'Q-MPRE-23', student:'law_quinn',
    request:'Does the conflict here require informed consent confirmed in writing?',
    response:'Yes — Model Rule 1.7(b) requires informed consent confirmed in writing when a concurrent conflict exists between current clients with adverse interests. Oral consent is insufficient.',
    ts:'May 16, 2026 · 12:50 PM' },
  { id:'fb-7816', rating:'up',   product:'CPA OLD',    qbank:null,
    contentType:'—',         contentId:null,        student:'legacy_dana',
    request:'Walk me through the steps to compute consolidated net income for a subsidiary acquired mid-year.',
    response:'Use partial-year consolidation: include the subsidiary\'s revenues and expenses from the acquisition date forward. Allocate any acquired in-process R&D, push down fair-value adjustments, and amortize identifiable intangibles only for the post-acquisition period.',
    ts:'May 16, 2026 · 11:08 AM' },
];

// ─────────────────────────────────────────────────────────────────────────────
//  GENERAL ROWS  (session removed from linked objects per spec)
// ─────────────────────────────────────────────────────────────────────────────
export const GENERAL_ROWS: GeneralRow[] = [
  { id:'gf-2041', rating:5, product:'Medical',    qbank:'USMLE Step 2 CK', student:'ipatel_03',      ts:'May 19, 2026 · 5:02 PM',
    feedback:'uAsk has become indispensable for my dedicated prep. The follow-up question feature lets me chase down a concept three layers deep without leaving the question, and the answers feel like talking to a senior resident. Please don\'t change the conversational tone.', linked:null },
  { id:'gf-2040', rating:2, product:'Medical',    qbank:'USMLE Step 1',    student:'mkr_med24',      ts:'May 19, 2026 · 4:39 PM',
    feedback:'Response was confidently wrong — gave me an outdated algorithm that no longer matches the 2024 AHA guidelines. I checked against First Aid and the lecture is correct. Please flag this to the medical team.',
    linked:{ contentType:'Question', contentId:'Q-9921',
      request:'What\'s the current first-line therapy for unstable bradycardia under the new AHA algorithm?',
      response:'Begin with atropine 0.5 mg IV every 3–5 minutes up to 3 mg total, then escalate to transcutaneous pacing or dopamine/epinephrine infusion. Identify and treat reversible causes early (H\'s and T\'s).' }},
  { id:'gf-2039', rating:4, product:'Nursing',    qbank:'NCLEX-RN',        student:'rn_jasmine',     ts:'May 19, 2026 · 3:11 PM',
    feedback:'Great feature overall. One small request — when I ask for a mnemonic, please return one mnemonic instead of three variants. I lose time picking between them.', linked:null },
  { id:'gf-2038', rating:1, product:'AP SCIENCE', qbank:'AP Biology',      student:'ap_neha',        ts:'May 19, 2026 · 2:24 PM',
    feedback:'The response cited a "Nobel Prize 2018 for photosynthesis" which does not exist. This is exactly the kind of fabrication that erodes trust. Please add a citation or source mode for science answers.',
    linked:{ contentType:'Article', contentId:'A-074',
      request:'Why is the light-dependent stage of photosynthesis considered the rate-limiting step?',
      response:'Recent work — including the 2018 Nobel Prize for photosynthesis research — has shown that electron transport across photosystem II is the rate-limiting step, governed by plastoquinone availability and the photodamage repair cycle of D1 protein.' }},
  { id:'gf-2037', rating:5, product:'Pre Med',    qbank:'USMLE Step 1',    student:'premed_lucy',    ts:'May 19, 2026 · 1:54 PM',
    feedback:'The conversational follow-ups for biochem are absurdly helpful. I went from 504 to 517 in three months and uAsk explanations were a huge part of that.', linked:null },
  { id:'gf-2036', rating:3, product:'CPA CMA',    qbank:'CPA',             student:'cpa_blake',      ts:'May 19, 2026 · 12:18 PM',
    feedback:'Answers for ASC 842 lease questions are usually fine but the response got the threshold wrong (said 80 % instead of 90 %). Please double-check the percentages it cites — those are the parts students will quote on the exam.',
    linked:{ contentType:'Question', contentId:'Q-3412',
      request:'What\'s the present-value threshold for finance-lease classification under ASC 842?',
      response:'Under ASC 842 a lease is finance if the present value of lease payments equals or exceeds 80 % of the underlying asset\'s fair value at commencement. This replaced the older 90 % rule under ASC 840.' }},
  { id:'gf-2035', rating:5, product:'AP SCIENCE', qbank:'AP Chemistry',    student:'ap_chen',        ts:'May 19, 2026 · 10:42 AM',
    feedback:'Worth every penny just for uAsk. I asked it to walk me through Le Châtelier on an equilibrium I\'d misread three times and it caught my mistake immediately.', linked:null },
  { id:'gf-2034', rating:2, product:'SAT & ACT',  qbank:'SAT',             student:'satprep_olivia', ts:'May 19, 2026 · 9:30 AM',
    feedback:'On reading-passage questions, the AI explains why the right answer is right but rarely explains why the trap answers are wrong — that\'s actually what I need help with. Could there be a "why are the other choices wrong?" button?',
    linked:{ contentType:'Question', contentId:'Q-S-218',
      request:'Why is (B) the correct answer to passage 4, question 17?',
      response:'Choice (B) correctly identifies the shift in the speaker\'s perspective between paragraphs 2 and 4 — from skepticism to grudging admiration — which is the central rhetorical movement of the passage.' }},
  { id:'gf-2033', rating:4, product:'CFA CMT',    qbank:'CFA Level I',     student:'cfa_ravi',       ts:'May 18, 2026 · 7:11 PM',
    feedback:'Solid on quant. A bit verbose on FRA questions — would love a "TL;DR" mode for when I just need the bottom line on a journal-entry question.', linked:null },
  { id:'gf-2032', rating:1, product:'Legal',      qbank:'MBE',             student:'esquire_jordan', ts:'May 18, 2026 · 6:02 PM',
    feedback:'Got an answer about Erie doctrine that conflated federal common law with state substantive law — this is a critical bar topic and the AI was misleading. Please review.',
    linked:{ contentType:'Question', contentId:'Q-L-401',
      request:'Under Erie, does a federal court sitting in diversity apply federal common law to substantive issues?',
      response:'Yes — when sitting in diversity, federal courts apply federal common law to substantive issues such as contract interpretation, while applying state law to procedural matters.' }},
  { id:'gf-2031', rating:5, product:'AP HISTORY', qbank:'AP US History',   student:'apush_mason',    ts:'May 18, 2026 · 4:55 PM',
    feedback:'uAsk\'s ability to compare two historical interpretations side-by-side is fantastic for DBQ prep. Honestly more useful than my study group.', linked:null },
  { id:'gf-2030', rating:5, product:'Pharmacy',   qbank:'NAPLEX',          student:'pharmd_alex',    ts:'May 18, 2026 · 3:33 PM',
    feedback:'The renal-dose-adjustment workflow is exactly what I needed for board prep. Suggest adding a hover-tooltip for drug brand names — sometimes I forget which generic.', linked:null },
  { id:'gf-2029', rating:3, product:'Nursing',    qbank:'NCLEX-RN',        student:'rn_devon',       ts:'May 18, 2026 · 2:28 PM',
    feedback:'The reply talks about "priority" actions a lot, but didn\'t actually use ABC ordering. For NCLEX every priority answer is essentially ABC-CAB. Tighten this up.',
    linked:{ contentType:'Question', contentId:'Q-N-771',
      request:'What\'s the priority intervention for suspected pulmonary embolism?',
      response:'First, notify the provider and prepare to administer anticoagulation. Then obtain a stat CT-PA and arrange transfer to a higher level of care for monitoring.' }},
  { id:'gf-2028', rating:4, product:'Medical',    qbank:'USMLE Step 2 CK', student:'drchen_md',      ts:'May 18, 2026 · 12:01 PM',
    feedback:'Generally accurate. Suggestion — when citing dose ranges, include the maximum safe dose by default. The current answers give "starting dose" which residents sometimes interpret as "the" dose.', linked:null },
  { id:'gf-2027', rating:5, product:'SAT & ACT',  qbank:'ACT',             student:'act_taylor',     ts:'May 18, 2026 · 10:22 AM',
    feedback:'uAsk caught a careless arithmetic mistake I\'d made and walked me back to where I went wrong. That\'s been my biggest weakness — game-changer.', linked:null },
  { id:'gf-2026', rating:2, product:'CPA CMA',    qbank:'CMA',             student:'cma_priya',      ts:'May 17, 2026 · 10:14 PM',
    feedback:'It told me a price variance was "usually unfavorable when actual cost exceeds standard." That\'s only true if quantity is the same — completely missed the spending variance distinction. Confusing for new learners.',
    linked:{ contentType:'Article', contentId:'A-CMA-31',
      request:'When is a direct-materials price variance favorable vs unfavorable?',
      response:'A price variance is favorable when the actual price paid is less than the standard price for the materials actually purchased, and unfavorable when actual price exceeds standard. This is true regardless of quantity.' }},
  { id:'gf-2025', rating:4, product:'AP MATH',    qbank:'AP Calculus AB',  student:'ap_riley',       ts:'May 17, 2026 · 7:08 PM',
    feedback:'Mostly good. When you give a graph in plain text, please use a fixed-width font — half the time the axis labels don\'t line up and I have to redraw it.', linked:null },
  { id:'gf-2024', rating:5, product:'Medical',    qbank:'USMLE Step 1',    student:'mvasquez_med',   ts:'May 17, 2026 · 5:01 PM',
    feedback:'I asked uAsk to teach me the same MG mechanism three different ways (cellular, clinical, exam-vignette) and it nailed each angle. This is the most useful AI tool I\'ve used in med school.', linked:null },
  { id:'gf-2023', rating:3, product:'CPAC',       qbank:null,              student:'cpac_haruki',    ts:'May 17, 2026 · 1:44 PM',
    feedback:'Answers are sometimes "US-GAAP-by-default" when I\'m clearly studying IFRS material. Could the AI auto-detect that I\'m in a CPAC product and bias toward IFRS?',
    linked:{ contentType:'—', contentId:null,
      request:'How do we account for development costs?',
      response:'Under US GAAP, development costs are expensed as incurred per ASC 730, with narrow exceptions for internal-use software (ASC 350-40). Capitalization is not permitted in most cases.' }},
  { id:'gf-2022', rating:5, product:'AP SCIENCE', qbank:'AP Psychology',   student:'psych_sam',      ts:'May 17, 2026 · 10:46 AM',
    feedback:'I love that uAsk gives me the textbook definition and then a real-world example. The dual-format works really well for my retention.', linked:null },
  { id:'gf-2021', rating:1, product:'AP SCIENCE', qbank:'AP Physics 1',    student:'phys_jin',       ts:'May 17, 2026 · 9:01 AM',
    feedback:'Said momentum was conserved "only in elastic collisions." This is the textbook backwards. If a student trusts this they\'ll lose easy points. Please flag for content review urgently.',
    linked:{ contentType:'Lecture', contentId:'L-PHY-14',
      request:'Is momentum conserved in inelastic collisions?',
      response:'Momentum is conserved only in elastic collisions. In inelastic collisions, kinetic energy is lost as heat or sound, and momentum is not strictly conserved either — though it\'s often close enough to use as an approximation for AP-level problems.' }},
  { id:'gf-2020', rating:4, product:'Legal',      qbank:'MBE',             student:'law_quinn',      ts:'May 16, 2026 · 4:48 PM',
    feedback:'Helpful, but the ABA Model Rule citations should link out to the rule text. Right now I\'m copy-pasting rule numbers to Google.', linked:null },
  { id:'gf-2019', rating:2, product:'CFA CMT',    qbank:'CFA Level II',    student:'cfa2_naomi',     ts:'May 16, 2026 · 2:55 PM',
    feedback:'The H-model explanation conflated H (half-life of high growth) with the full transition period. This is a common mix-up and the AI walked right into it. Worth a content fix.',
    linked:{ contentType:'Question', contentId:'Q-CFA2-77',
      request:'What does H represent in the H-model?',
      response:'H represents the full length of the high-growth transition period — i.e. the number of years over which growth declines linearly from g_s to g_L. So a 10-year transition is H = 10.' }},
  { id:'gf-2018', rating:5, product:'Nursing',    qbank:'NCLEX-PN',        student:'lpn_morgan',     ts:'May 16, 2026 · 12:11 PM',
    feedback:'Passed NCLEX-PN on first try. uAsk\'s ABG breakdowns and lab-value cheat-sheets carried me. Telling everyone in my cohort.', linked:null },
  { id:'gf-2017', rating:4, product:'AP ELA LOTE',qbank:null,              student:'apenglish_bea',  ts:'May 16, 2026 · 9:32 AM',
    feedback:'Strong on rhetorical analysis. Could the synthesis-essay feedback be more specific about which source-integration moves work and which don\'t? Generic "use more evidence" isn\'t enough.', linked:null },
  { id:'gf-2016', rating:3, product:'Pre Med',    qbank:'USMLE Step 1',    student:'mcat_yuna',      ts:'May 15, 2026 · 8:08 PM',
    feedback:'CARS explanations sometimes treat the passage as if it\'s making a single argument when MCAT CARS passages are usually layered. The AI needs to recognize tension within a passage, not just the main idea.',
    linked:{ contentType:'Question', contentId:'Q-M-414',
      request:'What is the main argument of passage 3?',
      response:'The author argues that contemporary urban planning has failed to balance pedestrian and vehicular needs, and that European models of mixed-use design offer a clear solution. This is the central claim across all five paragraphs.' }},

  // ── No-rating rows (user submitted text but did not give a star rating) ─
  { id:'gf-2015', rating:null, product:'Medical',    qbank:'USMLE Step 2 CK', student:'drlee_intern',   ts:'May 15, 2026 · 3:22 PM',
    feedback:'The AI explanation for Whipple procedure indications was accurate but skipped the classic contraindications. Would be more useful if it consistently mentioned what rules something out, not just what rules it in.', linked:null },
  { id:'gf-2014', rating:null, product:'Nursing',    qbank:'NCLEX-RN',        student:'rn_britta',      ts:'May 14, 2026 · 11:47 AM',
    feedback:'Delegation and prioritization questions are my weak spot and uAsk has been genuinely helpful. I just wish the explanations cited the NCLEX activity statements more explicitly so I can cross-reference my study guide.',
    linked:{ contentType:'Question', contentId:'Q-4471',
      request:'Which patient should the RN delegate to the LPN?',
      response:'The RN should delegate the stable post-op patient on day 2 who needs routine vital signs to the LPN. Delegation follows the Five Rights: right task, right circumstance, right person, right direction, and right supervision. Unstable or complex assessments must remain with the RN.' }},
  { id:'gf-2013', rating:null, product:'CPA CMA',    qbank:'CPA',             student:'cpa_felix',      ts:'May 13, 2026 · 7:55 PM',
    feedback:'Really appreciate the step-by-step journal entry walkthroughs. One thing — when the question involves a correction of an error from a prior period, the AI sometimes forgets to mention the retained earnings adjustment. Please review those cases.', linked:null },
  { id:'gf-2012', rating:null, product:'AP SCIENCE', qbank:'AP Biology',      student:'bio_kenji',      ts:'May 13, 2026 · 2:10 PM',
    feedback:'Great tool overall. The free-response feedback is much better than what my teacher gives in terms of specificity. Only suggestion: add a confidence indicator so I know which parts of the explanation are well-established vs. more interpretive.',
    linked:{ contentType:'Article', contentId:'A-BIO-88',
      request:'Explain how the lac operon switches between active and inactive states.',
      response:'When lactose is absent, the repressor protein binds the operator and blocks RNA polymerase. When lactose is present, allolactose (a metabolite) binds the repressor, causing a conformational change that releases it from the operator, allowing transcription of the structural genes lacZ, lacY, and lacA.' }},
];
